version: '3.4'

services:
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        container_name: amazing-db
        hostname: amazingdb
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Dockersql123#
            - MSSQL_PID=Express
        ports:
            - "1433:1433"
        networks:
         - amazing-dev

    amazingstore.api:
        image: ${DOCKER_REGISTRY-}amazingstoreapi
        container_name: amazing-store-api
        environment:
            - ConnectionString=db
        build:
            context: .
            dockerfile: AmazingStore.Api/Dockerfile       
        depends_on:
            - db
        networks:
         - amazing-dev

networks:
    amazing-dev:
        driver: bridge